name: Build

on:
  workflow_dispatch:
  push:
    branches: '**'
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
      - name: Check OpenSSL version
        run: openssl version
      - name: Check OpenSSH version
        run: ssh -V
      - name: Check Node version
        run: node -v
      - name: Check NPM version
        run: npm -v
