name: Build and Test VSCode extension

on:
  push:
    branches: '**'
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        runtime: [ linux, mac, windows ]
        include:
        - runtime: linux
          os: ubuntu-latest
          setupCmd: ./src/test/resources/ci/scripts/setup.sh
          execCmd: ./src/test/resources/ci/scripts/exec.sh

        - runtime: mac
          os: macOS-latest
          setupCmd: ./src/test/resources/ci/scripts/setup.sh
          execCmd: ./src/test/resources/ci/scripts/exec.sh

        - runtime: windows
          os: windows-latest
          setupCmd: bash ./src/test/resources/ci/scripts/setup.sh
          execCmd: bash ./src/test/resources/ci/scripts/exec.sh

    name: Build Plugin
    runs-on: ${{ matrix.os }}

    steps:
      # Checkout the eclipse plugin repository.
      - name: 'Setup: Checkout plugin'
        uses: actions/checkout@v3

      # Install the required software.
      - name: 'Setup: Install required software'
        run: ${{ matrix.setupCmd }}

      # Build the plugin.
      - name: 'Build: Build-Package-RunTests'
        continue-on-error: true
        run: ${{ matrix.execCmd }}

      # Archive artifacts
      - name: Archive artifacts
        if: runner.os == 'linux'
        uses: actions/upload-artifact@v3
        with:
          name: liberty-tools-vscode-${{ github.sha }}
          path: ./**/*.vsix
          if-no-files-found: warn
          retention-days: 7
